{% set version = "2.13" %}

package:
  name: lttng-ust
  version: {{ version }}

source:
  - url: http://lttng.org/files/lttng-ust/lttng-ust-latest-{{ version }}.tar.bz2
    sha256: 2cc42f51145050430ac4ab72b32d95fd78d5566ccbe44e14a8fcdd23c0ed8f6f

build:
  skip: true  # [win or osx]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - libuuid
    - popt
    - libxml2
  host:
    - liburcu
  run:
    - liburcu

test:
  commands:
    - test -e $PREFIX/include/lttng/tracepoint.h
    - test -e $PREFIX/lib/liblttng-ust.so

about:
  home: https://lttng.org/
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE
  summary: The LTTng User Space Tracing (LTTng-UST) library allows any C/C++ application to be instrumented for and traced by LTTng.
  doc_url: https://lttng.org/docs/v{{ version }}/
  dev_url: https://github.com/lttng/lttng-ust

extra:
  recipe-maintainers:
    - ZimmerA
    - wolfv
